#!/usr/bin/perl

if (@ARGV<4) {
	print  "programm repeat_list file_in file_out file_out2\n";
	exit;
}
($file_repeat,$file_in,$file_out,$file_out2) =@ARGV;

open IN,"$file_in" || die"$!";
open OUT,">$file_out" || die"$!";
open REPEAT,"$file_repeat";
open OUT2,">$file_out2";

#MER21B
#L1M2
#L1MB7
#L1MB1
#MER5B
#L1M4b
#MLT1G1
#L1MC4

while (<REPEAT>) {
	chomp;
	$repeat{$_} = 1;
}

#a score=432362.0
#human
#GGAAGCCTGTGGCTTAAAAAGGGCTGAATAACGACTGATATTCTCT-TCCTTCTCTCTTGGCTCTCACAGTCGAGGCTTTGGGCAATCCAACTCCCTCCCGACGGCTGGCTCTGTGGGCGGTGGCATGGGCAGACGGAACCCGCGCCAGTACCAGATCCCCTCTCGGAACGTCCCTTCCGCCCGCCTGGGCCTCTTGGGCACCAGTGGATTCGTCAGCTCCAACCAGCGCAACACCACAGCTACCCCCACCATCATGAAACAAGGAAGACAGGTTTGTTCTGCCCCAAGGAAGGAGGAGGA-TGGCC--AAGCTCAAGGCCCAAGGCTGC-AGATGTCCC---CCCAGGT-GACCCCAGGGTGGGGAGA-GAGGCCAAAGGGGACTATG---CTGG-GGGCAGTTGCCACCATTCCTCAGAGGTAACAGCA-TTGTTCGCGTTG-TTCTCTAGCAGACAGAGCAACCCCATAGCTG-TGTTT---------AGGATG-----------CCCAGAGGACCA-------CTTTAACCTTGGGGACCCTGCACAAGAGGACCTTTAGAAAGAAATGCAAGACCTATTTCT------TCTTTGCCCCA-TGCTTGACCTTC---------------TGCCACCCAAATCTGGGTTCCAGGAGAGC-CTGGCATTTAGAGAAGTTTCTTGCCCTTTTTATCCATGGCAAAAAGCTCCTTTGTCTCAGTCCCAGCTCTGGTGGAGCATCC--------ACAGGACAAAGTCTGAGAGAGTGTGCCAGGGGGAGAGTTAACACAT-----------TC----TCAGCCTGCCCAGAGGTTCTTGCTGTGCAGTTTAGAGCTGACTTCTCTGGCCCGTCGCTCATAC-CCCTCTAGCCCC-AGGCCCCACCCC-TGCCCAGTGCCTTCCGCCTGTGTGCCCAGAGCTTCTCGAAGCTCTGTGGGTAGGGATTAGGATCAGAGGGACA-CAAGTAGGTCTGAGGTTCTGGG-GTCTCAGGAGAAA-CTAAGGGATGACAGATCAGCTT--AAAAACAGG----AAAAGGGCTTCA----GGCAAGACGGGCAGGATTCACTACCCAGGG--------------TACCAGAAAGCCCCATCTTCTGACCATTGTCCCCAGCCCCCAGATCAGTTCAAGAAGACGTCACTGCTGGGAC------------------ACACAGGCTGAGT--TGTGCCAGCTCATTGCCAG--CTGAGAGTTTC-TTTTCTCTCCCCCTCGCTTTGGAGTACATTGTAAGAATCTTaaaaaaaaaaaaaaaaaaaaaaaaaaaTCAGAGCCCTGAAATAGTTTGTGCTCTTCGTTGCATACATTTATAG---AACTCCCCC----------------ATTTCCT-AGAAAAGTGGCAGGGAAAAAGCAAAAGCAACAAATGCGATAAAAAGAGTTCTGCAGATAGGGAAAGAGG----TGTCCAGATGAAGCTGAGGCTTACAGCAAGGCCACCACTGAGGAGGTGAAGAGAAA------TTACAGTGAATGG---AATCTAAACCCTCTCTCTATAAATAAGCAGATG-CTAGCACTGGCCTGCAAGCCCCTTTTCTAGAAGTT-----AGAGTTCTCCTGGGATCTTTGCCTCCCAAATTCTTGCTGGCGGCTCTG-CTCT------CC----------A---CCCCAGTGGGGCTGAACTAACAAGTTCCCCTTTTGCTTTTCTCACCAGAACCTGTGGTTTGCCAACCCCGGGGGCAGCAATAGCATGCCAAGCCGCACCCACAGCTCAGTCCAGAGGACCCGCTCGCTGCCCGTGCACACTTCCCCACAGAACATGCTGATGTTCCAGCAGCCAGGTAGGGCCCGG------CGCTTCAT--------------------------------------------------GTCCCCTTGAC--------ACAGAG--------GGGAGGCCAAAATAGATGCCCTAGCAAACCCAGCCAGAAAGTGCTTAGCCTCGACTGTCACCGTGCATTCTTTGGAGCTTATAGAAGCCTTTCCTTTTTTAAACTGTGCCTTGCCAGCATGAATAGCGGCGGCTTGGCTGAGAGCCAGCATGTGGAGCCCCAGAGTTGGTTGCAATCGG--ATGGGGATATTTTTGATACTAGTCA--------TATTTCTAGATTGATTAAACCAGAGATAGCAC-------AAGAGGGCTTTGGTGGTGGGG-AGGTGGGAGGG-CTCCAtgtgta--------gtgtgtgtgtgtgtgtgtg---------tgtgtgtgGAAAGAGAAAGTGAGAGTGAGACAGAGAAAGAGAAAACTGTT--------GAT-GCTGAGA-CCTTCCCCCTGGTTTGGGCTTTTCTTGCAAA-GTGATGACTGTTGTACCAGCCATCTTTCCTTTACTTGGTTAAAGAGCAACTT-----AGCACACTTCA
#6368	6394
#REPEAT:	  243   0.0  0.0  0.0  chr14_54306117_54418239_+      6368   6394 (105729) +  (A)n            Simple_repeat       1   27    (0)  340      
#7202	7234
#REPEAT:	  248   0.0  0.0  3.0  chr14_54306117_54418239_+      7202   7234 (104889) +  (TG)n           Simple_repeat       1   32    (0)  341      
#dog
#-----------GTTTGGGAAGGGCTGTG-GGTGACTGACAGGGTTT-CACTTGTCCATTCCCTCTCACAGCCGCGGCTTTGGGCAGTCCAACTCCCTCCCGACAGCCGGCTCTGTGGGCGGCGGTATGGGCCGACGGAACCCACGCCAGTACCAGATCCCCTCCCGGAACGTCCCTTCCGCCCGCCTTGGCCTCTTGGGCACCAGTGGATTTGTCAGCTCCACCCAGCGCAACACCACAGCCAACCCCACCATCATGAAACAAGGAAGACAGGTGTGTTCTGCCCCAGGGAGGAGGGTGGG-CAGCCTGAAGCTCAGGGCTTGAGGCTTCAGGGTCTATC---CCTACAT-GACCCCGAGGTGAGCAGA-GGAGTGGAGGAGGGCTGCA---CTGAGATACAGTTGTCCCTGTGC-TCAGAGGTAAC--CAGTTGTTTGCACTGTTTCCCTGGGAGACGGAGCAATGACCTGGCTG-CACTTGGCTTCATGGGGATTTACTTAGATGCCCTATGA--CCACTTTAACCTTTAACCTTGGGGGCTCTGTGCATTCGAGCCTTAAGGAGGAAATACAAGACCTATCTTG------GATTTGCCTTG---CTTGACCTGCCCCAGCAGACTTCACCACCTCCCAGATGTGGGTTCCAGAGA----CGAGCAGCTAAGGAGCTTTCTTAGCCTTTTTATTCACAGCAAATAGCTCCTTTGTCATGGTCCCAACTGTGGTAGAAAATCC--------AAAGAGG--AGCCTAAGAGAGGCTATCAGAGAGAGAATTGGAATATTCTCTCCCTATTCAAGGCCAGGCTGCCCAGAGGTCTTTACTGTGGGATTTAGAGCTGACTTCTAT--CCAAAGGCTTCTCA-CCCACCAGTCCTGTTCTCCCCACCC-TGCCCAATGCCTTCCATCAGTGTG--TCCAGCTTTGTGGGGCTCTGCAGGTTGGGGCTGGGACCGGAGGGATA-CAAGTGGGTCTGGG---------TTGTCATGAGAAACCTAAGGGATGATAGATTGGTTT--AAAAACAGGAAAAAAAACAGCTCCA----GGTAAAATGAGCAGGATTTATTTTCCAGGGCATATACAACAGCGTAGGAGAAAGCCCCACTTTCTGACCGTTGTGGGAAGCC-CCAAATCAGTTCAAGAGGAAGTCACCACTAGGACACCCGCATAATAATAA--ACGCAAGCTAAG---TGTGCCAGCTCATTGCCAG--CTGAAAGATTC-TTTTTTCTCCCCCTCGCTTTGTAGTAAGTTGTAAGACTCTC------------AAAAAGAAAATCAACTGAGAGCCCTGAAATAGTTTGTGCTCTTCGTTGCAAACATTTATAG---AACTCTTCC---------------CATCTCTGAAAAAAAGTGATAGG--AAAAGCAAAGGCAACAAAAGGAATAAAAAGAGTTTTGGAGATAGTGAGGAAGAGAGCTGTCCAGATTAAGCTAGGGTT--GAGCAAGGCC-----TTGGGCTTGGAGAGGGAG------AGAAAATGAATGG---ACTCTAAACCCCTTCTCTATAAATATGTAGATGTGTAGCATGAGCTTGCCAGGCCT-CTTCCAGAAGTTAGCAAAGGGTTCTCCAGGGGTATTTGCCTCTTGAATTCTGGCTGGCCGCCCTG-CTCCACACCCCCTCCGCCCCTGA---CCCCAAGGCATCTGGACTAAT-GGCTCTCCGTTTGCATTTCTCACTAGAACCTCTGGTTCGCCAATCCTGGGGGCAGCAACAGCATGCCAAGCCGCACCCACAGCTCAGTCCAAAGGACCCGCTCGTTGCCAGTGCACACTTCTCCGCAGAATATGCTGATGTTCCAGCAGCCAGGTAGGGCCCTG------TCCTTGAT---------------------------------------------CTCTCCCCCTCTCTTCCCCTTGACATGGAGGGGAGGCCAGGATGCCAAAATAGATGCCCCTGTGAACCCAGCCGGAAAGTGCTTAGCCTCGACTGTCACCACGCATTCTTTTGAGCTTATAGAAGCCTTTCCTTTTTTAAACTGTGCCTTGCCAGCATGAATAGCGGCTGGTTGGCTGGGAGCCAGCACATGGAGCCCCAGAGCCGGTTGCAATCTG--ACGGGGATATTTTTGATACTAGTCA--------TATTTCTAGATTGATTAAACCAGAGATATCAC-------TGGAGGGTATC----TGGGGG-AGTTGGGAGGGGTTCCAtgtgtcgtgcgcatgtgtgtctgtgtgtgtgtgtgctttgtgtgtatgtgGGAGGATGTGCAGAAAGTGAAACAGAAGAAGAGAAAACTTTGATGGCACTGACAGCTAAGAGACTTACCTCTGGTTTGGGAGTACCTTGCAAATGTGA--CTTATCGGACCAGCCATCTTCCCTTTACTTGGCTTAAGAGCAACTT-----GGTGCACTTCA
#2088	2137
#REPEAT:	  202  12.5  0.0  4.0  chr8_33570306_33655525_+     2088   2137  (83083) +  (TG)n           Simple_repeat       1   48    (0) 1290      
#mouse
#GGCAGCCTGGG--CTATGTAGGGCTGGA----GCCAGAACCTCTGG-ATCTCTTCTCTTTGCTCTCACAGTCGTGGCTTTGGGCAGTCCAACTCCCTCCCAACAGCCAGCTCTGTGGGCAGCGGCATGGGCAGACGGAACCCACGACAGTACCAGATCGCATCTCGGAATGTCCCTTCCGCCCGCCTTGGTCTCCTGGGCACCAGTGGATTTGTCAGCTCCAACCAGCGCCACACCGCTGCCAACCCCACCATCATGAAACAAGGAAGACAGGTTTGTTCTGCTCTGGGGAGCAGGGAGGT-TGACC--AAGCTCAGGGACTGAGGCTTTAAGATGTCTCCAACCCAGACAGTCTCCTGCATGGAAAGATAAGACCCCAGGGGAATCTAAACCAGG-AGATAGCTGAGCCTATGCTTGTCAGGTAAT--CA-CTGTTTGCGTTG-TTTCCCTGGAGACGGAA-AAACTCATGTCTGCTGCTT---------GGGAAA-----------GCTAGTG--CTA-------CATTTATCTCTGGGACCCT-------------TGTAGACAGGCATGCAAGGGCTACTTCTGCTTGATCTTTGCCCCC-CCCCCAACATACCC----------CATCACCTTCCAGGTCTGGGT-------------GGGCATTTAATAAGCTTCCTTTGACTTTTTCCTCA---------------------CAGTCCCGGCTGCAATGGTGAGTCC--------ACAGGAT--TGTTTGGGAGGCTGTCC-------------------------------------------------------CTTGCTGTGAGATTGACAG-TGACCTCTCTGCC----------------------CCCC-TGAGCCCAACCT-TGCCT--TTCCCTAAATGTTCATTCCCTCAGCCCCCTGAGGCAATAGAGGT-TGGCCTGGGCCTGGGAACATA-CAAGCAGGCCT--------------------------------GATGAGAGGTTGTCTT--TAAAACAG-------AAAGGCTTCACCAGGAGGAGGCTGGTGGCAGTCCCTCCCAATGG-------------------GAAGGGCATGTCTGAGA------------AGCCCTGATATCAGTTCTAGGCAAGGTCACTAC-AGGAC------------------ACACGAGCTGCATGATATACAGGCCTGTTGCCAGTACTGACTCTTTC-TTTTCT-----CCTCAGTGTGGAGTAAATTTGGGGACTCTC------------AAAAAGAAATTCAAATAAGAGCCTTAAACTCA-TTATACTGTTTGCTACAAGTATTTCTAAGACAACCCCCCCACACACACACACACATACTCCCT-TTAAGA----------------------AATATATGGAGTAAAAACACTTTTGGAGATGGGGAGAGGGG----------AAGGTGGCTCAAACTTAAAGCGAGGCC-----------TGTGAATGAGCC------TCA-----AATGGGACAGTCTCAGCCATCTCTCAGTAAGTCCATGGCGG-GTAGCATGGGCC-----------TTTCCAAAA------------CTGTCCTGGGATACCTGTCTCCCGAGTTCCAGCTGG-GGCTCTGCCTCC------CC----------ACATCCCCACAGGGTCTGGACTAATGCCCCCCTCTTGTATGTCCCTCCCTAGAACCTCTGGTTTGCCAACCCTGGGGGCAGCAACAGCATGCCCAGCCGCACCCACAGCTCCGTCCAGAAGACCCGCTCGCTGCCCGTGCATACTTCCCCACAAAACATGCTGATGTTCCAGCAACCAGGTAGGGCCTGGCTAACTCGCTCCCTtctctctctctctctctctctctctctctctctctctctctctctctctctctccctTGAC--------GCAGAATGGAGGCTGGGATGCCAGAATAGACGCCCTGGT-GACCCAGCCGGAAAGTGCTGAGCCTCAACTGTCACCACACATTCTTTAGAGCTGCCGAAAGCCTTTCCTTTTTTAAACCATGCCTTGCCAGTGTGAGCAGAGGCTGCCTAGCAGGGAGCCAGAGCCTGAAGTCCCAGCACTGGTTGCAATATA--ACAGGGATATTTCTGATACTTGTCAGATATCTGGATTCCTAGATTGATTAAACCAGCGATAGCTCTCCCTGGAAGAGATCCCT----GTGGAA-AGGTGGGGGGG----------------------------------GGGGG---------GATGTGTGCAAAGA------GAGGATAAGACAACAAAAGAGAAAAACTTG--------AAT-GTTGG------TGTCACTG---TGGAATGGCATTGGAAA-ACAG-------------AGCCATGGTTT-----CTTGATTCAGGAGTAACTTGACGGAGTGGACTCAA
#1508	1564
#REPEAT:	  492   1.8  0.0  0.0  chr14_39753339_39837733_+     1508   1564  (82831) +  (TC)n          Simple_repeat       2   58    (0) 1160      
#muntjac
#-----------GGCTGGGAAGGGCCGGG-GGTGACTGATGACCTCTGTTCTTCTCTATTGCCTCCCACAGCCGCGGCTTTGGGCAGTCCAACTCCCTCCCGACAGCCAGCTCTGTGGGTGGCGGCATGAGCAGACGCAACCCACGCCAGTACCAGATCCCCTCGCGGAATGTCCCTTCCGCCCGCCTTGGCCTCTTGGGCACCAGTGGATTCGTCAGCTCAACCCAGCGCAATACCGCAGCCAACCCCACCATCATGAAGCAAGGAAGACAGGTCTGCTCTGCCCCCGGGAGGAGGGTGGGCCAGCC--AAGCTCAGGGCCTGAGGC-TCAGGACATCCC---CCCAAAT-GACCCGAAGGCAAAGGGA-GAAGCGCAGAAGGGCTAGG---TTGA-AGACAGTTGCCCCTATGCTTCAGAGGT--------TTGTTTGCA--GTTTCTCTGGGAGATAAAGCAAGGCCATGGCGG-CACCTGGCACCATGGGGATT--------TGTTCCAAGG--CCA-------CTGTAAACTTGGGGGCCCTACCCAGAGTGGCCATTAGGAAGAAATGCAAGACCTATTTCA------TCTTTGCCTTGATCCTCAACTTGCCCTAGCAGATCCCAGTGCCTTCCAGGTTTGGCTTCCAGAGGAGCCTGAGCATCTAAGGAGCTTTCTTAGCGTTTATACCTGAGGCAGATAACTCCTTTGACATGGTCCCAGCTGTGATGGAAAACCCTACAGGGAAGGGAGG--AGACTGAGAGAGGCCATCAG----------------------------TCAAGGCCACGCTGCTGAGATATTCTCACTATGGGATTTAGAGCCACCATCAGT--CTCCTGGCTCGTCGTCTCGGGAGTCCC-TCCCCCTCACTCGTACCAGATGCCTCCCACCCGTGTAGCCCCTGCTTTGTGGGGCTCTGCGGGTGGGGGCTGGGATTAGAGGGACGCCGAGTGAGTCTGAGGTTCTGGATTTGTCACGAGAAA-CTAAAGGATGACAGCTTGGTTTTAAAAAACAGG-----AAACCGTTCCT----GGCAAGACAGGCAGGATTCACTCCCCCGGGGAAGCAGCCCAGGGTAGGAGAAAACCCCAGTCT-TGACCATTGTGGGAAGCCACCAGATGGATCCAGGAGGAAAGCAGCGCTAGGACACCCGCGTCATAACAAACACACAAGCTGAGT--TGTGCCAGCTCGCTGCCAG--CCGAGAGGTTCTTTTTTTCTCCTCCTTCCTTTGTAGTAAATTCTAGGAACCTC------------AAAGAGAAAATCAAATGAGAGCCCTGAAATAGTTTGTGCTCTTCGTTGCAGACATTTATAG---AACTCCCCC---------------CATTTCCT-AGAAAAGTGATAGG--AAAAGCAGAGACAACAGCAGGGATAAAAAGAGTTTTGGAGCCAGCGAGGGAGATTGGTGTCCAGATTAAGCTGAGGCTTAGAGAAGAGCC-----TGGGGCT--GAGGGGTAGTGTTGAATAAAATGAATGG---AATCTAAAGCCCCTCTCTCTAAATAAGCAGACAGATTGCGCTGGCCTAGGAGCTCT-TTCCCAGAAGTTAGCAGAGAGTTCTCCCAGGGTACCTGCCTCCTGGATTCTGGCTGGTGGCCCTG-CTCT-CATCCCC----------A---CCCCCAGGTGTCTGGACTGATGGGTTCTGCTTCTGTGTTTTTCCCTAGAACCTCTGGTTCGCCAACCCCGGGGGCAGCAATAGCATGCCAAGCCGCACCCACAGCTCTGTGCAAAGGACCCGCTCACTGCCTGTGCACACTTCACCACAGAACATGCTGATGTTCCAGCAGCCAGGTAGGGCCCAG------CCCTCCAT---------------------------------------------CCCTCGTCGTCCTGTC-------------GGGGAGGCCAGGTCACCAAAATAGATGCCCCAGTGAACTCAAGCGGAAAGTGCTTAGCCTCGACTGCCACCTTGCATTCTTTTGAGCTTATAGAAGCCTTTCCTTTTTTAAACCATGCCTTGCCAACATGAACAGCGGCTTGTTGGCTGGGAGCCAGCACACTGAGCCCCAGAGTTGGTTGCGATGTGACACGGGGGCATTTTGGATCCTAGTCA--------TATTTCTAGATTGATTAACCCAGTAACATCAC-------TGGAGGGCTTT----TGGGGGAAATTGAGAGGGGTTCCATGTATA--------gtgtgtgtgtgtgtgtgtgtgGTTGGTATGTACATAGGGTGATGTGTAG--------ATAGAGAAAGAGAAAACTCCG-TGGTGTTGAT-GCTGAGAGACCTACCCCTGGTTTGGGAGTGCTTTGCACACGTGA---TTGCTGGTCCATCCATCTTCCCTTTAGTTGGTTAAAGAGCAGCCT-----GGTGTGCACCA
#7416	7436
#REPEAT:	  189   0.0  0.0  0.0  bsba_459_92307_+      7416  7436 (84413) +  (TG)n         Simple_repeat       1   21    (0)  680      
#
#a score=43080.0
#human
#TTCATCAGTCACCTTGCTCGGGTTTACAGGACTCATCCCTCGTTCCTGGTTCTACACAATTCACGGGCA------CTTGGAGGCCCCTCAGGAGTGGTGTTTCATGTTATTCCCACATGGACAAGCtttttttttttttttttttcgagacggagtctcactctgtcacccaggctggagtacagtggcgcaatctcagctcactgcaacctccacct--tcACATGGACAAGTTTTAGCTGTTTCCTGGGACCAGCCAGGAGACCCTTCAGGT---GGCTATTGCCA-------------GTGATGAGTAAGAAACACT------------------ACGAGGT---------GTAATACGC-TCACCAG-----------------AAAACAAGTGTGGCGCCT-GTGCGAATGGTCACGTTCCTCATGGAGGCAGGGCGTTTTCTCAACTAGATAACTGGTTTGGAAATTGCTTGGA-GAGGGATCCTTT-ATTTTGGAAGCAACTA-ATTTCTACTGACCCAGGCTTAGTTGTCCTTGGGATCCAGTCAGAGAGGATCTTGGAGTGGCCCTGGCTCAACAGTAGGAGATCA-TGGAGGTTCTTTACCCCCTGGAGGGCCTAACAGAAAAGGGCAGGGAACCCCATAGCAGGCTT---CAAAGGAAAACCTTCAGA
#10031	10124
#REPEAT:	  745   8.5  0.0  0.0  chr14_54306117_54418239_+     10031  10124 (101999) C  AluSg/x         SINE/Alu         (10)  302    209  344      
#dog
#CTGATCAGTCACCTGGCTTGAGTTTGCAAGACGATCTAATCTTTCATGGATCTACAGGGTTTGTGG----------------ACCCCCTAGG------------------------------------------------------------AGG--------------CCATGTTTGGGGTAGT-------TTTTTAATTCATTC--------------CCAGAGGGACAGATTTTAGATGTTTCCCAGGACAAACCAAGAGAGCTACTAAGTTTAGATTGCTGCCTCTCACTGGCCTCTGGCATGAGTAAGAAACACTAACCTGGTCCTCC-CAAAGCAAGGGAGAGAGGGTCTGATAACACTCACCAGTGGAGTGACTTTAGCTCAGAACAAGTGTGGTGCCTGGT----GTGGTCACATTCCCCCAAAAGGCATGGTGTTTTCCCAACTGGAAAATTAGTTTGGAAATTGCTTGCA-AAATGACTACGTCATCTTGGAAGCAGATCTGTTCCTGCTGACCCATGCTCAGCCACCCTTGGGATCCAGTCAGAGAGAATCTCAAAACAGCTCTGGTGTAACACTGGGAGGCCA-CGGAGGCTCCTCACCACCTAGAGGGCCTGACAGGAAAGGGCCGAGGGACCAGAGGCTGACTT---TAAAAGAAAAGCATAgga
#4855	4857
#REPEAT:	  715   6.7  1.9  0.0  chr8_33570306_33655525_+     4855   4959  (80261) +  SINEC_Cf        SINE/Lys            2  108   (81) 1293      


$group1_num = 0;
$group2_num = 0;
while (<IN>) {
	chomp;
	push @lines,$_;
	if ($_=~/human|dog|mouse|muntjac/) {
		$specie = $_;
	}
	elsif ($_=~/REPEAT:\s+(.*)/){
		$repeatmasker = $1;
		@ss = split /\s+/,$repeatmasker;
		$old_repeat_name = $ss[9];
		$repeat_name = $ss[8]."-". $ss[9];
#		print "11 $repeat_name\n";
		if (exists $repeat{$old_repeat_name}) {
#			${$mark{$specie}}{$repeat_name} =1;
			${$repeat_mark{$repeat_name}}{$specie} = 1;
		}
	}
	elsif ($_ eq ""){
#		print "here!!\n";
		foreach my $repeat_key (keys %repeat_mark) {
#			print "$repeat_key\n";

			@species = keys %{$repeat_mark{$repeat_key}};
			$spe_num{$repeat_key} = scalar @species; # repeat 在物种中出现次数
#			print "@species\n";
			if (scalar @species >=2 && scalar @species <4) {# 出现2，3次
				$open2 = 1;
			}
			elsif (scalar @species ==4) {# 出现4次
				$open4 = 1;
			}

		}
		if ($open2 == 1) { # 出现2，3次
			$group1_num ++;
			print OUT "\nGroup:$group1_num\n=========\n";
			foreach my $line  (@lines) {
	#			print  "bbbbbbbbbbbbbb\n";
				if ($line=~/^REPEAT:\s+(.*)/) {
	#			print  "ccccccc\n";
					$repeat_mask = $1;
					@sk = split /\s+/,$repeat_mask;
					$repeat_name_here = $sk[8]."-".$sk[9];
#					print  "444444444444  $repeat_name_here\n";
					if (exists $spe_num{$repeat_name_here}) {
#						print  "REPEAT_NUM_HERE===$repeat_num_here\n";
						if ($spe_num{$repeat_name_here} >=2 && $spe_num{$repeat_name_here}<4) {
							print OUT "	$sk[4]\t$sk[5]\t$sk[6]\t$sk[9]\n";
						}
					}
				}
				elsif ($line=~/human|mouse|dog|muntjac/) {
					print OUT ">$line\n";
				}
			}
		}
		if ($open4 == 1) {# 出现4次
			$group2_num ++;
			print OUT2 "\nGroup:$group2_num\n=========\n";
		#	print  "000000000000000000000000\n";
			foreach my $line  (@lines) {
				if ($line=~/^REPEAT:\s+(.*)/) {
					$repeat_mask = $1;
					#print  "11111111 $repeat_mask\n";
					@sk = split /\s+/,$repeat_mask;
					$repeat_name_here = $sk[8]."-".$sk[9];
#					print  "444444444444  $repeat_name_here\n";
					if (exists $spe_num{$repeat_name_here}) {
#						print  "REPEAT_NUM_HERE===$repeat_name_here\n";
						if ($spe_num{$repeat_name_here} ==4) {
							print OUT2 "	$sk[4]\t$sk[5]\t$sk[6]\t$sk[9]\n";
						}
					}
				}
				elsif ($line=~/human|mouse|dog|muntjac/) {
					print OUT2 ">$line\n";
				}
			}
		}
		%repeat_mark = ();
		$open2 = 0;
		$open4 = 0;
		%spe_num = ();
		@lines =();
	}
}


# Last Line~~~
#
		foreach my $repeat_key (keys %repeat_mark) {
#			print "$repeat_key\n";

			@species = keys %{$repeat_mark{$repeat_key}};
			$spe_num{$repeat_key} = scalar @species; # repeat 在物种中出现次数
#			print "@species\n";
			if (scalar @species >=2 && scalar @species <4) {# 出现2，3次
				$open2 = 1;
			}
			elsif (scalar @species ==4) {# 出现4次
				$open4 = 1;
			}

		}
		if ($open2 == 1) { # 出现2，3次
			$group1_num ++;
			print OUT "\nGroup:$group1_num\n=========\n";
			foreach my $line  (@lines) {
	#			print  "bbbbbbbbbbbbbb\n";
				if ($line=~/^REPEAT:\s+(.*)/) {
	#			print  "ccccccc\n";
					$repeat_mask = $1;
					@sk = split /\s+/,$repeat_mask;
					$repeat_name_here = $sk[8]."-".$sk[9];
#					print  "444444444444  $repeat_name_here\n";
					if (exists $spe_num{$repeat_name_here}) {
#						print  "REPEAT_NUM_HERE===$repeat_num_here\n";
						if ($spe_num{$repeat_name_here} >=2 && $spe_num{$repeat_name_here}<4) {
							print OUT "	$sk[4]\t$sk[5]\t$sk[6]\t$sk[9]\n";
						}
					}
				}
				elsif ($line=~/human|mouse|dog|muntjac/) {
					print OUT ">$line\n";
				}
			}
		}
		if ($open4 == 1) {# 出现4次
			$group2_num ++;
			print OUT2 "\nGroup:$group2_num\n=========\n";
		#	print  "000000000000000000000000\n";
			foreach my $line  (@lines) {
				if ($line=~/^REPEAT:\s+(.*)/) {
					$repeat_mask = $1;
					#print  "11111111 $repeat_mask\n";
					@sk = split /\s+/,$repeat_mask;
					$repeat_name_here = $sk[8]."-".$sk[9];
#					print  "444444444444  $repeat_name_here\n";
					if (exists $spe_num{$repeat_name_here}) {
#						print  "REPEAT_NUM_HERE===$repeat_name_here\n";
						if ($spe_num{$repeat_name_here} ==4) {
							print OUT2 "	$sk[4]\t$sk[5]\t$sk[6]\t$sk[9]\n";
						}
					}
				}
				elsif ($line=~/human|mouse|dog|muntjac/) {
					print OUT2 ">$line\n";
				}
			}
		}
		%repeat_mark = ();
		$open2 = 0;
		$open4 = 0;
		%spe_num = ();
		@lines =();
